name: .NET Build & Release

on:
  push:
    branches:
      - dev
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: microsoft/setup-msbuild@v1.1

      - uses: NuGet/setup-nuget@v1.0.5

      - name: Restore Packages
        run: nuget restore ToNStatTool.sln

      - name: Build solution
        run: msbuild ToNStatTool.sln -t:rebuild -property:Configuration=Release

      - name: Zip output
        run: powershell compress-archive .\ToNStatTool\bin\Release\* Release.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ToNStatTool_release
          path: Release.zip

  release:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: windows-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ToNStatTool_release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          files: Release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
